<x-main menu='HOME'>
  <div>
    <img src="{{ url('/image/home/Urban-Athletes-Banner-Home.jpg') }}" alt="Urban Athletes">
  </div>
  <div class="container">
      <h1 class="">Home</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci molestias id assumenda corporis! Aut quas necessitatibus, iusto assumenda nihil voluptate, est doloribus molestias blanditiis, beatae ea explicabo vero praesentium non?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ipsa dolore pariatur veniam inventore corporis consequuntur excepturi, velit in provident aspernatur eius hic quas magni eligendi qui, natus illo quam quis. Sunt accusantium, tempore qui eius dolor dolores ratione temporibus debitis est exercitationem totam error minima cupiditate alias rem earum voluptatum aspernatur delectus. Dolores nulla aperiam at commodi laborum, inventore cupiditate ut atque repellendus corporis dolorem itaque eligendi ea autem natus quo voluptate. Ea pariatur repellendus tempora eaque libero nostrum, quae quasi soluta porro, tempore nam quis. Distinctio, modi! Tenetur rerum quidem odio commodi distinctio ratione, pariatur impedit nulla provident!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ipsa dolore pariatur veniam inventore corporis consequuntur excepturi, velit in provident aspernatur eius hic quas magni eligendi qui, natus illo quam quis. Sunt accusantium, tempore qui eius dolor dolores ratione temporibus debitis est exercitationem totam error minima cupiditate alias rem earum voluptatum aspernatur delectus. Dolores nulla aperiam at commodi laborum, inventore cupiditate ut atque repellendus corporis dolorem itaque eligendi ea autem natus quo voluptate. Ea pariatur repellendus tempora eaque libero nostrum, quae quasi soluta porro, tempore nam quis. Distinctio, modi! Tenetur rerum quidem odio commodi distinctio ratione, pariatur impedit nulla provident!</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur ipsa dolore pariatur veniam inventore corporis consequuntur excepturi, velit in provident aspernatur eius hic quas magni eligendi qui, natus illo quam quis. Sunt accusantium, tempore qui eius dolor dolores ratione temporibus debitis est exercitationem totam error minima cupiditate alias rem earum voluptatum aspernatur delectus. Dolores nulla aperiam at commodi laborum, inventore cupiditate ut atque repellendus corporis dolorem itaque eligendi ea autem natus quo voluptate. Ea pariatur repellendus tempora eaque libero nostrum, quae quasi soluta porro, tempore nam quis. Distinctio, modi! Tenetur rerum quidem odio commodi distinctio ratione, pariatur impedit nulla provident!</p>
  </div>
</x-main>