<x-main_web menu='ABOUT US' subMenu="TERMS & CONDITIONS">
  <div class="flex justify-center max-h-[30vh] lg:max-h-[40vh] relative">
    <img class="object-cover object-top w-full mx-auto lg:-mt-20" src="{{ url('image/web/about/UA-Banner_Global.jpg') }}" alt="About Us Urban Athletes">
    <div class="absolute top-0 bottom-0 left-0 right-0 flex flex-col justify-center items-center text-white bg-gradient-to-t from-black">
      <div class="absolute bottom-0 max-w-max text-center pb-8">
        <h2 class="text-4xl font-FuturaBold pb-2 lg:pb-4">TERMS & CONDITIONS</h2>
        {{-- <P>
          HOME <span class="text-yellow-primary">|</span> TERMS & CONDITIONS
        </P> --}}
      </div>
    </div>
  </div>
  <div class="container py-8">
    <div class="px-4 md:px-8 pb-8">
      <ol class="list-decimal">
        <li class="py-2">Anggota harus mempunyai kewenangan untuk mengikat diri pada perjanjian ini. Jika anggota tidak mempunyai kewenangan penuh maka anggota harus menyatakan dan menjamin bahwa persetujuan dari wali yang sah menurut hukum telah diperoleh sebelum menandatangani perjanjian ini. Anggota menyatakan bahwa dia telah menerima copy dari perjanjian ini. Perjanjian ini juga berfungsi sebagai dasar untuk menggunakan fasilitas-fasilitas klub sampai anggota menerima kartu anggota tetap. Anggota menyetujui segala ketentuan keanggotaan yang tercantum dalam klub serta ketentuan dalam perjanjian ini. URBAN Athlete Berhak merubah ketentuan ketentuan tersebut dari waktu ke waktu.</li>
        <li class="py-2">Dalam hal keanggotaan PIF (Paid in Full/ keanggotaan dibayar dimuka dalam jangka waktu tertentu) dipilih sebagaimana tercantum pada bagian Detail Keanggotaan, anggota berhak untuk menggunakan fasilitas klub secara berkelanjutan selama jangka waktu PREPAID TERM. Setelah jangka waktu tersebut anggota dapat memilih untuk memperbaharui keanggotaannya sesuai dengan biaya biaya yang tercantum dalam jenis keanggotaan di masa yang akan datang.</li>
        <li class="py-2">Dalam hal jenis keanggotaan EFT (Electronic Fund Transfer) dipilih sebagaimana tercantum pada bagian Detail Keanggotaan, anggota tersebut tidak dapat membatalkan perintah pembayaran melalui kartu kredit sampai jangka waktu minimum telah terlampaui anggota dapat mengakhiri keanggotaannya dengan memberitahukan secara tertulis dalam jangka waktu tidak kurang dari 10 hari kerja sebelum tanggal jatuh tempo pemotongan biaya keanggotaan berikutnya. Pemberitahuan tertulis harus diberikan secara langsung kepada Receptionist kami. Copy persetujuan pembatalan akan diberikan secara langsung kepada anggota sebagai bukti dari pengakhiran perjanjian. Dalam hal anggota memberikan pemberitahuan tertulis kurang dari 10 hari kerja sebelum tanggal jatuh tempo pemotongan biaya keanggotaan. Anggota akan tetap dibebankan biaya keanggotaan dan anggota tersebut berhak atas penggunaan fasilitas club untuk waktu 60 hari setelah tanggal jatuh tempo pembayaran. Biaya keanggotaan EFT akan naik sebesar 5% per 12 bulan keanggotaan yang terhitung sejak tanggal aktivasi membership. Cancellation Fee sebesar 20% dari sisa nominal kontrak akan diberlakukan jika anggota tidak sesuai kontrak membership MINIMAL 12 bulan keanggotaan membership aktif.</li>
        <li class="py-2">Anggota diijinkan untuk membekukan (freezing) membershipnya apabila tidak bisa datang ke club untuk jangka waktu lebih dari 1(satu) bulan dengan biaya pembekuan sebesar Rp. 100.000,- per bulan dengan maksimum total pembekuan adalah 12 bulan maksimal 3 kali dalam setahun. Proses pembekuan untuk membership EFT harus diajukan secara tertulis selambat lambat nya 10 hari sebelum tanggal jatuh tempo pendebetan berikut nya. Pembekuan membership diluar bulan puasa dan hari besar agama harus menyertakan supporting document.</li>
        <li class="py-2">Membership tidak dapat dipindah tangankan dari satu orang ke orang lain dalam periode yang sama dengan alasan apapun.</li>
        <li class="py-2">Anggota berhak mentransfer membershipnya (1) satu kali saja ke kerabat atau rekannya dengan alasan kehamilan, atau pindah luar kota dengan menunjukkan dokumen pendukung. Setelah dipindah tangankan anggota lama tidak boleh menggunakan fasilitas URBAN Fitness lagi ataupun menerima transfer dari memebrship yang sama. Biaya untuk satu kali transfer membership adalah Rp. 250,000,-.</li>
        <li class="py-2">Seluruh biaya bulanan dan pembayaran yang jatuh tempo setiap bulannya harus dibayar dimuka melalui pemotongan langsung melalui kartu kredit. Jika anggota lalai untuk membayar kewajiban pembayaran bulanan yang telah jatuh tempo, URBAN Fitness berhak untuk menolak anggota tersebut untuk memasuki area URBAN Athlete sampai pembayaran atas tunggakan diterima. URBAN Athlete berhak untuk mengambil segala tindakan hukum untuk mendapatkan tunggakan pembayaran. Anggota harus menanggung seluruh biaya yang dikeluarkan oleh URBAN Athlete berkaitan dengan tindakan hukum tersebut. Anggota tetap berkewajiban untuk membayar biaya keanggotaan dan pembayaran yang telah jatuh tempo selama periode tersebut.</li>
        <li class="py-2">Untuk keselamatan, kenyamanan dan kepentingan anggota lain, URBAN Athlete berhak untuk mengakhiri SECARA SEPIHAK keanggotaan dari anggota yang telah melanggar syarat-syarat dan ketentuan dalam perjanjian ini dan peraturan dan ketentuan umum yang berlaku di dalam Urban Athletes. Berkaitan dengan hal ini tidak ada biaya biaya yang dikembalikan kepada anggota terkait.</li>
        <li class="py-2">Seorang anggota harus memperlihatkan kartu keanggotaannya atau kartu identitasnya setiap kali datang ke URBAN Athletes. Jika kartu tersebut hilang atau dicuri, maka anggota tersebut harus segera menghubungi klub untuk mendapatkan kartu pengganti. Anggota tersebut bertanggung jawab terhadap biaya penggantian kartu sebesar Rp. 50,000,-</li>
        <li class="py-2">Anggota berhak untuk menggunakan fasilitas Locker yang ada di Ruang ganti Pria maupun wanita. Akan tetapi perlu di ingat bahwa anggota WAJIB mengeluarkan barang yang ditaruh di dalam locker sebelum meninggalkan Gym setiap hari nya. Semua barang yang tertinggal di locker akan kami keluarkan setiap hari dan akan kami simpan di Lost & Found kami selama paling lama 14 hari sejak tanggal pertama ditemukan. Barang yang tidak diambil setelah 14 hari akan kami sumbangkan ke organisasi social atau kami musnahkan. Anggota dikenakan biaya denda Rp, 50,000,- yang harus dibayarkan pada saat pengambilan barang yang tertinggal tersebut.</li>
        <li class="py-2">Anggota dilarang memberikan pelatihan pada anggota lain dengan alasan apapun, apabila dari pihak kami menemukan hal tersebut, maka kami berhak menterminasi/ mengakhiri membership anggota tersebut secara sepihak dan tidak ada pengembalian uang dalam bentuk apapun.</li>
        <li class="py-2">Anggota HARUS menggunakan sepatu dan pakaian olah raga yang layak. Anggota yang tidak memakai sepatu ataupun pakaian olah raga yang layak TIDAK DIPERKENANKAN masuk dan olah raga di dalam Gym. Anggota juga berkewajiban untuk memelihara semua properti di dalam Gym. Tidak diperkennkan untuk membanting beban secara tidak wajar, dan harus meletakkan kembali alat alat yang telah dipakai ke tempat semula. pelanggaran akan hal ini akan dikenakan surat peringatan tertulis, dan bila terulang setelah adanya surat peringatan akan mengakibatkan terminasi sepihak dari Pihak Urban Athlete, dan tidak ada pengembalian uang dalam bentuk apapun.</li>
        <li class="py-2">Anggota wajib mengganti segala macam bentuk kerusakan yang tidak wajar yang ditimbulkan karena kelalaian maupun kesengajaan sejumlah nilai beli barang tersebut di waktu kerusakan tersebut terjadi, atau menggantinya dengan barang yang sama persis. Adapun bila barang yang dimaksud sudah tidak diproduksi lagi, maka jumlah kerugian yang dibayarkan adalah sejumlah faktur pembelian barang tersebut semulajadi. Keputusan ini adalah mutlak dan tidak dapan di ganggu gugat.</li>
        <li class="py-2">
          Tamu yang dibawa untuk coba gratis haruslah:
          <ul class="list-disc pl-4">
            <li class="py-1">Penduduk kota Surabaya (atau yang memiliki bukti domisili di Surabaya)</li>
            <li class="py-1">Berusia diatas 18 tahun, orang tua harus mendampingi anak-anak berusia antara 13 hingga 18 tahun.</li>
            <li class="py-1">Mengisi formulir formulir yang diperlukan</li>
          </ul>
        </li>
        <li class="py-2">Mereka yang bukan anggota, termasuk anak kecil dibawah 13 tahun TIDAK diperkenankan untuk memasuki area gym. Mereka hanya diperkenankan untuk menunggu di lobby dengan satu orang dewasa sebagai pengawas.</li>
        <li class="py-2">Kelas pribadi untuk Pilates, Crossfit dan Personal Trainer dikenakan biaya tambahan sesuai paket dan promosi yang berlaku pada saat itu.</li>
        <li class="py-2">Kelas TRX, RPM, Muaythai, Fitball, Fly High Yoga, Wheel Yoga, Body Pump atau  kelas dengan tempat terbatas. Peserta wajib mendaftar terlebih dahulu. Pendaftaran akan dibuka 60 menit sebelum kelas dimulai. Pendaftaran tidak bisa diwakilkan maupun via telepon.</li>
        <li class="py-2">Kamera foto atau alat perekam video lain termasuk telepon genggam dan perlengkapannya dilarang digunakan untuk memotret atau merekam di dalam lokasi URBAN Athletes khususnya di ruang ganti dan di ruang latihan.</li>
        <li class="py-2">Anggota wajib berhati hati dalam menggunakan alat dan fasilitas Gym. Anggota wajib meletakkan kembali alat yang dipakai di arena Gym ke tempat yang seharus nya. Pelanggaran akan hal ini akan mendapatkan teguruan dari Departement Operational dan Personal Trainer. Mengabaikan teguran ini akan mengakibatkan pemutusan membership secara sepihak dan tidak aka nada pengembalian uang yang telah dibayarkan dengan alasan apapun.</li>
        <li class="py-2">Untuk keanggotaan EARLY RISER, adapun ketentuan pemakaian fasilitas gym hingga jam 16.00 WIB. Apabila melebihi batas waktu yang ditentukan akan dikenakan biaya penalty sebesar Rp. 20.000,- untuk 30 menit pertama, 30 menit berikutnya kelipatan Rp. 10.000,-</li>
        <li class="py-2"><b>Late Payment</b> Rp. 20.000,- / bulan. Apabila dilakukan >15 hari dari tanggal <b>billing autodebet.</b></li>
        <li class="py-2">Perlu diketahui bahwa segala publisitas buruk terkait Urban Athletes dilindungi oleh <b>pasal 310 KUHP</b> tentang pencemaran nama baik. Segala macam keluhan, kritik dan saran bisa disalurkan dengan menghubungi No WA <b>(081)79188880</b> atau Email <b>wecare@urbanathletes.co.id.</b></li>
      </ol>
    </div>
  </div>
</x-main_web>